// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     backends/cpp/templates/function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/pose3.h>

namespace sym {

/**
 * Composition of two elements in the group.
 *
 * Returns:
 *     res_D_a: (6x6) jacobian of res (6) wrt arg a (6)
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 6> ComposePose3Jacobian0(const sym::Pose3<Scalar>& a,
                                                  const sym::Pose3<Scalar>& b) {
  // Total ops: 193

  // Input arrays
  const Eigen::Matrix<Scalar, 7, 1>& _a = a.Data();
  const Eigen::Matrix<Scalar, 7, 1>& _b = b.Data();

  // Intermediate terms (73)
  const Scalar _tmp0 = _a[0] * _b[2];
  const Scalar _tmp1 = -_tmp0;
  const Scalar _tmp2 = _a[2] * _b[0];
  const Scalar _tmp3 = -_tmp2;
  const Scalar _tmp4 = _a[3] * _b[1];
  const Scalar _tmp5 = _a[1] * _b[3];
  const Scalar _tmp6 = _tmp4 - _tmp5;
  const Scalar _tmp7 = _tmp1 + _tmp3 + _tmp6;
  const Scalar _tmp8 = _tmp4 + _tmp5;
  const Scalar _tmp9 = _tmp1 + _tmp2 + _tmp8;
  const Scalar _tmp10 = _a[2] * _b[3];
  const Scalar _tmp11 = _a[3] * _b[2];
  const Scalar _tmp12 = _a[0] * _b[1];
  const Scalar _tmp13 = _a[1] * _b[0];
  const Scalar _tmp14 = _tmp12 - _tmp13;
  const Scalar _tmp15 = _tmp10 + _tmp11 + _tmp14;
  const Scalar _tmp16 = -_tmp10;
  const Scalar _tmp17 = _tmp12 + _tmp13;
  const Scalar _tmp18 = _tmp11 + _tmp16 + _tmp17;
  const Scalar _tmp19 = _a[0] * _b[3];
  const Scalar _tmp20 = -_tmp19;
  const Scalar _tmp21 = _a[3] * _b[0];
  const Scalar _tmp22 = -_tmp21;
  const Scalar _tmp23 = _a[2] * _b[1];
  const Scalar _tmp24 = _a[1] * _b[2];
  const Scalar _tmp25 = _tmp23 - _tmp24;
  const Scalar _tmp26 = _tmp20 + _tmp22 + _tmp25;
  const Scalar _tmp27 = _tmp19 + _tmp21 + _tmp25;
  const Scalar _tmp28 = _a[2] * _b[2];
  const Scalar _tmp29 = _a[3] * _b[3];
  const Scalar _tmp30 = _a[1] * _b[1];
  const Scalar _tmp31 = _a[0] * _b[0];
  const Scalar _tmp32 = _tmp30 - _tmp31;
  const Scalar _tmp33 = _tmp28 + _tmp29 + _tmp32;
  const Scalar _tmp34 = _tmp30 + _tmp31;
  const Scalar _tmp35 = -_tmp29;
  const Scalar _tmp36 = _tmp28 + _tmp34 + _tmp35;
  const Scalar _tmp37 = _a[0] * _a[2];
  const Scalar _tmp38 = _a[1] * _a[3];
  const Scalar _tmp39 = _tmp37 + _tmp38;
  const Scalar _tmp40 = _a[0] * _a[1];
  const Scalar _tmp41 = _a[2] * _a[3];
  const Scalar _tmp42 = _tmp40 - _tmp41;
  const Scalar _tmp43 = std::pow(_a[0], Scalar(2));
  const Scalar _tmp44 = std::pow(_a[1], Scalar(2));
  const Scalar _tmp45 = -_tmp44;
  const Scalar _tmp46 = std::pow(_a[2], Scalar(2));
  const Scalar _tmp47 = std::pow(_a[3], Scalar(2));
  const Scalar _tmp48 = _tmp46 - _tmp47;
  const Scalar _tmp49 = _tmp43 + _tmp45 + _tmp48;
  const Scalar _tmp50 = _a[1] * _a[2];
  const Scalar _tmp51 = _a[0] * _a[3];
  const Scalar _tmp52 = _tmp50 - _tmp51;
  const Scalar _tmp53 = 2 * _b[5];
  const Scalar _tmp54 = -_tmp43;
  const Scalar _tmp55 = _tmp45 + _tmp46 + _tmp47 + _tmp54;
  const Scalar _tmp56 = _tmp50 + _tmp51;
  const Scalar _tmp57 = 2 * _b[6];
  const Scalar _tmp58 = -_tmp28;
  const Scalar _tmp59 = _tmp32 + _tmp35 + _tmp58;
  const Scalar _tmp60 = _tmp23 + _tmp24;
  const Scalar _tmp61 = _tmp20 + _tmp21 + _tmp60;
  const Scalar _tmp62 = _tmp0 + _tmp3 + _tmp8;
  const Scalar _tmp63 = -_tmp11;
  const Scalar _tmp64 = _tmp10 + _tmp17 + _tmp63;
  const Scalar _tmp65 = _tmp44 + _tmp48 + _tmp54;
  const Scalar _tmp66 = 2 * _b[4];
  const Scalar _tmp67 = _tmp40 + _tmp41;
  const Scalar _tmp68 = _tmp37 - _tmp38;
  const Scalar _tmp69 = _tmp29 + _tmp34 + _tmp58;
  const Scalar _tmp70 = _tmp14 + _tmp16 + _tmp63;
  const Scalar _tmp71 = _tmp19 + _tmp22 + _tmp60;
  const Scalar _tmp72 = _tmp0 + _tmp2 + _tmp6;

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 6> _res_D_a;

  _res_D_a(0, 0) = -_tmp15 * _tmp18 - _tmp26 * _tmp27 - _tmp33 * _tmp36 - _tmp7 * _tmp9;
  _res_D_a(1, 0) = -_tmp15 * _tmp33 + _tmp18 * _tmp36 - _tmp26 * _tmp7 + _tmp27 * _tmp9;
  _res_D_a(2, 0) = _tmp15 * _tmp27 - _tmp18 * _tmp26 + _tmp33 * _tmp9 - _tmp36 * _tmp7;
  _res_D_a(3, 0) = 2 * _b[5] * _tmp39 - 2 * _b[6] * _tmp42;
  _res_D_a(4, 0) = _b[6] * _tmp49 + _tmp52 * _tmp53;
  _res_D_a(5, 0) = _b[5] * _tmp55 - _tmp56 * _tmp57;
  _res_D_a(0, 1) = -_tmp15 * _tmp59 - _tmp26 * _tmp62 + _tmp36 * _tmp64 + _tmp61 * _tmp9;
  _res_D_a(1, 1) = _tmp15 * _tmp64 + _tmp26 * _tmp61 + _tmp36 * _tmp59 + _tmp62 * _tmp9;
  _res_D_a(2, 1) = _tmp15 * _tmp62 - _tmp26 * _tmp59 + _tmp36 * _tmp61 - _tmp64 * _tmp9;
  _res_D_a(3, 1) = -_b[6] * _tmp65 - _tmp39 * _tmp66;
  _res_D_a(4, 1) = -2 * _b[4] * _tmp52 + 2 * _b[6] * _tmp67;
  _res_D_a(5, 1) = -_b[4] * _tmp55 + _tmp57 * _tmp68;
  _res_D_a(0, 2) = -_tmp15 * _tmp71 + _tmp26 * _tmp70 + _tmp36 * _tmp72 - _tmp69 * _tmp9;
  _res_D_a(1, 2) = _tmp15 * _tmp72 - _tmp26 * _tmp69 + _tmp36 * _tmp71 - _tmp70 * _tmp9;
  _res_D_a(2, 2) = -_tmp15 * _tmp70 - _tmp26 * _tmp71 - _tmp36 * _tmp69 - _tmp72 * _tmp9;
  _res_D_a(3, 2) = _b[5] * _tmp65 + _tmp42 * _tmp66;
  _res_D_a(4, 2) = -_b[4] * _tmp49 - _tmp53 * _tmp67;
  _res_D_a(5, 2) = 2 * _b[4] * _tmp56 - 2 * _b[5] * _tmp68;
  _res_D_a(0, 3) = 0;
  _res_D_a(1, 3) = 0;
  _res_D_a(2, 3) = 0;
  _res_D_a(3, 3) = 1;
  _res_D_a(4, 3) = 0;
  _res_D_a(5, 3) = 0;
  _res_D_a(0, 4) = 0;
  _res_D_a(1, 4) = 0;
  _res_D_a(2, 4) = 0;
  _res_D_a(3, 4) = 0;
  _res_D_a(4, 4) = 1;
  _res_D_a(5, 4) = 0;
  _res_D_a(0, 5) = 0;
  _res_D_a(1, 5) = 0;
  _res_D_a(2, 5) = 0;
  _res_D_a(3, 5) = 0;
  _res_D_a(4, 5) = 0;
  _res_D_a(5, 5) = 1;

  return _res_D_a;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
