# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/namespace_init.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

__path__ = __import__("pkgutil").extend_path(__path__, __name__)  # type: ignore  # mypy issue #1422
